name: "🐞 Bug report"
description: Report a reproducible problem
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: ["noobychris"]
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **Before reporting a bug, please re-run your test with the following options enabled:**
        ```python
        ENABLE_LOGGING = True
        show_can_messages_in_logs = True
        ```
        This will generate more detailed logs and speed up troubleshooting.
        *(You can disable them again afterwards.)*

  - type: dropdown
    id: car_model
    attributes:
      label: Vehicle model
      description: Select the tested model
      options:
        - "-- Please choose --"
        - Audi A4 8E (B6/B7)
        - Audi A3 8L
        - Audi A3 8P
        - Audi TT 8J
        - Audi R8 42
        - Other / Unknown
    validations:
      required: true

  - type: input
    id: car_model_other
    attributes:
      label: Specify vehicle model (if "Other / Unknown")
      placeholder: e.g., Audi A6 C5

  - type: dropdown
    id: rpi_model
    attributes:
      label: Raspberry Pi
      options:
        - "-- Please choose --"
        - Raspberry Pi 3B
        - Raspberry Pi 3B+
        - Raspberry Pi 4 (2/4/8GB)
        - Other / Unknown
    validations:
      required: true

  - type: input
    id: rpi_model_other
    attributes:
      label: Specify Raspberry Pi model (if "Other / Unknown")
      placeholder: e.g., Raspberry Pi 5

  - type: dropdown
    id: can_module
    attributes:
      label: CAN module / interface
      options:
        - "-- Please choose --"
        - PiCan2
        - PiCan3
        - vcan0 (virtual)
        - Other / Unknown
    validations:
      required: true

  - type: input
    id: can_module_other
    attributes:
      label: Specify CAN module (if "Other / Unknown")
      placeholder: e.g., custom Arduino CAN interface

  - type: input
    id: function_name
    attributes:
      label: Function name or section causing the error (optional)
      description: If known, please specify the Python function, method, or section of the script where the error occurs.
      placeholder: e.g., def read_canbus()

  - type: input
    id: version
    attributes:
      label: Script version / commit
      description: E.g. tag or short SHA (git rev-parse --short HEAD)
      placeholder: e.g. 0.5.2 or a1b2c3d
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Exact steps, commands, and settings to trigger the bug
      placeholder: |
        1. …
        2. …
        3. …
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior / screenshots
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        Please attach relevant log excerpts from `script_folder/logs/DATE_TIME_read_from_canbus_errors.log`  
        Example: `2025_07_03-12:30:12_read_from_canbus_errors.log`  
        Redact personal info if needed.

  - type: textarea
    id: extra
    attributes:
      label: Additional context
