name: "🚗 Compatibility report"
description: Report a (partially) compatible vehicle
title: "[Compatibility]"
labels: ["compatibility", "triage"]
assignees: ["noobychris"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing! Please fill out the fields as accurately as possible.  
        For better verification, logs are highly appreciated (see below).

  - type: input
    id: model
    attributes:
      label: Model
      description: e.g. "Audi A4", "Audi A3", "Audi TT"
      placeholder: Audi A4
    validations:
      required: true

  - type: input
    id: type
    attributes:
      label: Type
      description: e.g. "8E", "8P", "8J"
      placeholder: 8E
    validations:
      required: true

  - type: input
    id: year
    attributes:
      label: Year (optional)
      description: e.g. "2004" (leave empty if unknown)
      placeholder: 2004

  - type: dropdown
    id: dis_fis
    attributes:
      label: DIS/FIS output working?
      options:
        - "-- Please choose --"
        - "Yes"
        - "No"
        - "Not tested"
    validations:
      required: true

  - type: dropdown
    id: mfsw
    attributes:
      label: MFSW (multi-function steering wheel) working?
      options:
        - "-- Please choose --"
        - "Yes"
        - "No"
        - "Not installed"
        - "Not tested"
    validations:
      required: true

  - type: textarea
    id: works
    attributes:
