name: Auto-title Compatibility Issues
on:
  issues:
    types: [opened, edited]

jobs:
  auto_title:
    if: contains(join(github.event.issue.labels.*.name, ','), 'compatibility')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Build dynamic title from form fields
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const body = issue.body || '';

            function extract(label) {
              const re = new RegExp(`###\\s+${label}[\\r\\n]+([\\s\\S]*?)(?:\\r?\\n\\r?\\n|$)`, 'i');
              const m = body.match(re);
              if (!m) return '';
              // take first non-empty line
              const firstLine = m[1].split('\n').map(s => s.trim()).find(Boolean) || '';
              return firstLine.replace(/^"|"$/g, '').trim();
            }

            const model = extract('Model');
            const type  = extract('Type');
            const year  = extract('Year \\(optional\\)');

            const parts = [model, type, year].filter(Boolean);
            if (parts.length) {
              const newTitle = `[Compatibility]: ${parts.join(' ')}`;
              if (issue.title !== newTitle) {
                await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  title: newTitle
                });
              }
            }
